package com.deluxedemo.deluxemodels;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ComputerRequest implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("CPU Family")
	private java.lang.String cpu;
	@org.kie.api.definition.type.Label("RAM")
	private java.lang.String ram;
	@org.kie.api.definition.type.Label("Screen Size")
	private java.lang.String screensize;
	@org.kie.api.definition.type.Label("Operating System")
	private java.lang.String operatingSystem;
	@org.kie.api.definition.type.Label("Price")
	private java.lang.Double price;
	@org.kie.api.definition.type.Label("System Type ( New / Refurbished )")
	private java.lang.String type;

	@org.kie.api.definition.type.Label(value = "Hardware")
	private java.lang.String hardware;

	public ComputerRequest() {
	}

	public java.lang.String getCpu() {
		return this.cpu;
	}

	public void setCpu(java.lang.String cpu) {
		this.cpu = cpu;
	}

	public java.lang.String getRam() {
		return this.ram;
	}

	public void setRam(java.lang.String ram) {
		this.ram = ram;
	}

	public java.lang.String getScreensize() {
		return this.screensize;
	}

	public void setScreensize(java.lang.String screensize) {
		this.screensize = screensize;
	}

	public java.lang.String getOperatingSystem() {
		return this.operatingSystem;
	}

	public void setOperatingSystem(java.lang.String operatingSystem) {
		this.operatingSystem = operatingSystem;
	}

	public java.lang.Double getPrice() {
		return this.price;
	}

	public void setPrice(java.lang.Double price) {
		this.price = price;
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public java.lang.String getHardware() {
		return this.hardware;
	}

	public void setHardware(java.lang.String hardware) {
		this.hardware = hardware;
	}

	public ComputerRequest(java.lang.String cpu, java.lang.String ram,
			java.lang.String screensize, java.lang.String operatingSystem,
			java.lang.Double price, java.lang.String type,
			java.lang.String hardware) {
		this.cpu = cpu;
		this.ram = ram;
		this.screensize = screensize;
		this.operatingSystem = operatingSystem;
		this.price = price;
		this.type = type;
		this.hardware = hardware;
	}

}