package com.deluxedemo.deluxemodels;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Contact implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Address")
	private java.lang.String address;
	@org.kie.api.definition.type.Label(value = "City")
	private java.lang.String city;
	@org.kie.api.definition.type.Label(value = "ZipCode")
	private java.lang.String zipcode;

	public Contact() {
	}

	public java.lang.String getAddress() {
		return this.address;
	}

	public void setAddress(java.lang.String address) {
		this.address = address;
	}

	public java.lang.String getCity() {
		return this.city;
	}

	public void setCity(java.lang.String city) {
		this.city = city;
	}

	public java.lang.String getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(java.lang.String zipcode) {
		this.zipcode = zipcode;
	}

	public Contact(java.lang.String address, java.lang.String city,
			java.lang.String zipcode) {
		this.address = address;
		this.city = city;
		this.zipcode = zipcode;
	}

}