package com.deluxedemo.deluxemodels;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Employee implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Employee Identifier")
	private java.lang.Integer employeeId;
	@org.kie.api.definition.type.Label("Name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label("Hire Date")
	private java.util.Date dateofHire;
	@org.kie.api.definition.type.Label("Role")
	private java.lang.String role;
	private java.lang.String type;
	@org.kie.api.definition.type.Label("Hiring Location")
	private java.lang.String location;
	@org.kie.api.definition.type.Label("Contact")
	private com.deluxedemo.deluxemodels.Contact contact;

	@org.kie.api.definition.type.Label("Requested Machine")
	private com.deluxedemo.deluxemodels.ComputerRequest requestedMachine;

	@org.kie.api.definition.type.Label("Assigned Machine")
	private com.deluxedemo.deluxemodels.ComputerRequest assignedMachine;

	@org.kie.api.definition.type.Label("Email Address")
	private java.lang.String emailAddress;

	@org.kie.api.definition.type.Label(value = "Annual Salary")
	private java.lang.Double annualSalary;

	@org.kie.api.definition.type.Label(value = "Hourly Rate")
	private java.lang.Double hourlyRate;

	public Employee() {
	}

	public java.lang.Integer getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(java.lang.Integer employeeId) {
		this.employeeId = employeeId;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.util.Date getDateofHire() {
		return this.dateofHire;
	}

	public void setDateofHire(java.util.Date dateofHire) {
		this.dateofHire = dateofHire;
	}

	public java.lang.String getRole() {
		return this.role;
	}

	public void setRole(java.lang.String role) {
		this.role = role;
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public java.lang.String getLocation() {
		return this.location;
	}

	public void setLocation(java.lang.String location) {
		this.location = location;
	}

	public com.deluxedemo.deluxemodels.Contact getContact() {
		return this.contact;
	}

	public void setContact(com.deluxedemo.deluxemodels.Contact contact) {
		this.contact = contact;
	}

	public com.deluxedemo.deluxemodels.ComputerRequest getRequestedMachine() {
		return this.requestedMachine;
	}

	public void setRequestedMachine(
			com.deluxedemo.deluxemodels.ComputerRequest requestedMachine) {
		this.requestedMachine = requestedMachine;
	}

	public com.deluxedemo.deluxemodels.ComputerRequest getAssignedMachine() {
		return this.assignedMachine;
	}

	public void setAssignedMachine(
			com.deluxedemo.deluxemodels.ComputerRequest assignedMachine) {
		this.assignedMachine = assignedMachine;
	}

	public java.lang.String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(java.lang.String emailAddress) {
		this.emailAddress = emailAddress;
	}

	public java.lang.Double getAnnualSalary() {
		return this.annualSalary;
	}

	public void setAnnualSalary(java.lang.Double annualSalary) {
		this.annualSalary = annualSalary;
	}

	public java.lang.Double getHourlyRate() {
		return this.hourlyRate;
	}

	public void setHourlyRate(java.lang.Double hourlyRate) {
		this.hourlyRate = hourlyRate;
	}

	public Employee(java.lang.Integer employeeId, java.lang.String name,
			java.util.Date dateofHire, java.lang.String role,
			java.lang.String type, java.lang.String location,
			com.deluxedemo.deluxemodels.Contact contact,
			com.deluxedemo.deluxemodels.ComputerRequest requestedMachine,
			com.deluxedemo.deluxemodels.ComputerRequest assignedMachine,
			java.lang.String emailAddress, java.lang.Double annualSalary,
			java.lang.Double hourlyRate) {
		this.employeeId = employeeId;
		this.name = name;
		this.dateofHire = dateofHire;
		this.role = role;
		this.type = type;
		this.location = location;
		this.contact = contact;
		this.requestedMachine = requestedMachine;
		this.assignedMachine = assignedMachine;
		this.emailAddress = emailAddress;
		this.annualSalary = annualSalary;
		this.hourlyRate = hourlyRate;
	}

}